/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : RX671_MCR.c
*  Description  : Main Program
*  Creation Date: 2025-04-29
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "r_sdc_sd_rx_if.h"
#include "r_sdhi_rx_if.h"
#include "r_cmt_rx_if.h"
#include "r_pinset.h"
// #include "r_tfat_driver_rx_if.h"

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#include "ff.h"
#include "diskio.h"

#include "timer.h"
#include "BMI088.h"
#include "ssd1351.h"
#include "WS2812C.h"
#include "switch.h"

#define CMT_CHANNEL 0
#define SD_CARD_NO  0

uint32_t work[200 / sizeof(uint32_t)];
sdc_sd_cfg_t sdc_sd_config;
// uint8_t errorflg = 0;
sdc_sd_status_t errorflg1;
sdc_sd_status_t errorflg2;
sdc_sd_status_t errorflg3;

FATFS *fs;        // ファイルシステムオブジェクト
FIL file;        // ファイルオブジェクト
UINT bw, br;     // 書き込み／読み込みバイト数
char write_data[] = "Hello, RX1 SD card!\r\n";
char read_buf[64];

void main(void);

void main(void)
{
	FRESULT res;

	// R_Config_SCI2_Start();

	
	R_SDHI_PinSetInit();
	R_SDHI_PinSetDetection();

	R_CMT_CreatePeriodicAssignChannelPriority(1000, &interrupt1ms, CMT_CHANNEL, (cmt_priority_t)CMT_PRIORITY_5);

	errorflg1 = R_SDC_SD_Open(SD_CARD_NO, SDHI_CH0, work);
	errorflg2 = R_SDC_SD_GetCardDetection(SD_CARD_NO);

	sdc_sd_config.mode = SDC_SD_MODE_POLL | SDC_SD_MODE_SW | SDC_SD_MODE_MEM | SDC_SD_MODE_4BIT;
	sdc_sd_config.voltage = SDC_SD_VOLT_3_3;

	PORT7.PODR.BIT.B4 = 0; // SDカードの電源ON
	cnt0 = 0;
	// while (1)// SDカードの電源ON待ち
	// {
	// 	if (cnt0 > 1000)
	// 	{
	// 		break;
	// 	}	
	// } 
	R_BSP_SoftwareDelay(1000,BSP_DELAY_MILLISECS);

	R_SDHI_PinSetTransfer();
	errorflg3 = R_SDC_SD_Initialize(SD_CARD_NO, &sdc_sd_config, SDC_SD_MODE_MEM);

	// 既存マウントを解除（安全のため）
	fs = malloc(sizeof (FATFS));
    res = f_mount(fs, "0:", 0);

    // 書き込みテスト：ファイル新規作成
    res = f_open(&file, "0:test.txt", FA_CREATE_ALWAYS | FA_WRITE);
    if (res == FR_OK)
    {
		f_printf(&file, "Hello SD printf %f",0.1);
        f_close(&file);
    }

    // 読み込みテスト
    res = f_open(&file, "0:test.txt", FA_READ);
    if (res == FR_OK)
    {
        // f_read(&file, read_buf, sizeof(read_buf) - 1, &br);
		f_gets(read_buf, sizeof(read_buf), &file);
        f_close(&file);
    }

    // アンマウント（任意）
    f_mount(NULL, "0:", 0);


	// initIMU = BMI088init();
	// SSD1351init();

	// 赤枠描画
	// for(int x = 0; x < SSD1351_WIDTH; x++) {
    //     SSD1351drawPixel(x, 0, SSD1351_RED);
    //     SSD1351drawPixel(x, SSD1351_HEIGHT-1, SSD1351_RED);
    // }

    // for(int y = 0; y < SSD1351_HEIGHT; y++) {
    //     SSD1351drawPixel(0, y, SSD1351_RED);
    //     SSD1351drawPixel(SSD1351_WIDTH-1, y, SSD1351_RED);
    // }

	// R_BSP_SoftwareDelay(1000,BSP_DELAY_MILLISECS);
	// // R_Config_CMT0_Start(); // タイマ割り込みスタート
	// calibratIMU = true;	// IMUキャリブレーション開始
	// while(calibratIMU);	// キャリブレーション完了待ち
	
	// setLED(0, 5, 0, 0);
	// setLED(1, 5, 0, 0);
	// setLED(2, 5, 0, 0);
	// setLED(3, 5, 0, 0);
	// sendLED();

	while (1)
	{
		// SSD1351setCursor(2,2);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"x:%4d",(int32_t)BMI088val.angle.x);
		// SSD1351setCursor(2,13);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"y:%4d",(int32_t)BMI088val.angle.y);
		// SSD1351setCursor(2,24);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"z:%4d",(int32_t)BMI088val.angle.z);
		// SSD1351setCursor(60,2);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"temp:%2d",(int32_t)BMI088val.temp);
		// SSD1351setCursor(2, 35);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"5ax:%x",swValTact);
		// SSD1351setCursor(40, 35);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"Rotary:%x",swValRotary);

	}
}
