/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : RX671_MCR.c
*  Description  : Main Program
*  Creation Date: 2025-04-29
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include "r_cmt_rx_if.h"
#include "r_dmaca_rx_if.h"

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#include "timer.h"
#include "BMI088.h"
#include "ssd1351.h"
#include "gui.h"
#include "WS2812C.h"
#include "switch.h"
#include "SDcard.h"
#include "encoder.h"
#include "Motor.h"

#define CMT_CHANNEL 0

char read_buf[64];

void main(void);

void main(void)
{
	volatile FRESULT res;

	// タイマ割り込み開始(1ms)
	R_CMT_CreatePeriodicAssignChannelPriority(1000
											, &interrupt1ms
											, CMT_CHANNEL
											, (cmt_priority_t)CMT_PRIORITY_5);
	R_DMACA_Init(); // DMAC内部情報を初期化

	R_Config_SCI2_Start();
	BMI088init();
    SSD1351init();
    GUI_ShowStartup();

    // 赤枠描画
	for(int x = 0; x < SSD1351_WIDTH; x++) {
        SSD1351drawPixel(x, 0, SSD1351_RED);
        SSD1351drawPixel(x, SSD1351_HEIGHT-1, SSD1351_RED);
    }

    for(int y = 0; y < SSD1351_HEIGHT; y++) {
        SSD1351drawPixel(0, y, SSD1351_RED);
        SSD1351drawPixel(SSD1351_WIDTH-1, y, SSD1351_RED);
    }

	R_BSP_SoftwareDelay(1000,BSP_DELAY_MILLISECS);
	calibratIMU = true;	// IMUキャリブレーション開始
	while(calibratIMU);	// キャリブレーション完了待ち
	
	// SDカード初期化
	if(SDcardOpen() == SDC_SD_SUCCESS)
	{
		SDcardinit(); // SDカード初期化
	}
	if(initSDcard)
	{
		// res = logCreate();
		// if (res == FR_OK)
		// {
		// 	loggingSDcard = 1;
		// 	cnt0 = 0;
		// }
	}

	InitEncoder();
	InitMotor();

	R_Config_S12AD0_Start(); // A/D変換開始
	R_Config_S12AD1_Start(); // A/D変換開始
	
	// SSD1351drawImage(0, 0, 128, 128, imgQRgithub128x128);
	// initLED();
	// setLED(0, 255, 0, 0);
	// setLED(1, 255, 0, 0);
	// setLED(2, 255, 0, 0);
	// setLED(3, 255, 0, 0);
	// sendLED();
	cnt0 = 0;
	PORTB.PODR.BIT.B4 = 0;

	SSD1351fill(SSD1351_BLACK);

	// 電源電圧を表示
	GetBatteryVoltage();
	GUI_ShowStatusBar();

	const char *menu_items[] = {
		  "START   "
		, "SETTINGS"
		, "INFO1   "
		, "INFO2   "
		, "INFO3   "
		, "INFO4   "
		, "INFO5   "
		, "INFO6   "
		, "INFO7   "
		, "INFO8   "
		, "INFO9   "
		, "INFO10  "
		, "INFO11  "
		, "INFO12  "
		, "INFO13  "
	};
    GUI_ShowMenu(menu_items, 14, 0, 0);

	while (1)
	{
		if(!insertSDcard && initSDcard)
		{
			// SDカードが抜かれた場合の処理
			SDcardEnd(); // SDカードの終了処理
		} else if(insertSDcard && !initSDcard)
		{
			SDcardinit(); // SDカードの初期化
		}

		GUI_MenuSelect(menu_items, 14);

		// SSD1351setCursor(2,2);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"x:%4d",(int32_t)BMI088val.angle.x);
		// SSD1351setCursor(2,14);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"y:%4d",(int32_t)BMI088val.angle.y);
		// SSD1351setCursor(2,26);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"z:%4d",(int32_t)BMI088val.angle.z);
		// SSD1351setCursor(60,2);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"temp:%2d",(int32_t)BMI088val.temp);
		// SSD1351setCursor(60,14);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"cnt:%5d",cnt0);
		// SSD1351setCursor(2, 38);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"Rotary:%x",swValRotary);
		// SSD1351setCursor(85, 38);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"5ax:%x",swValTact);
		// SSD1351setCursor(2, 50);
		// // SSD1351printf(Font_7x10,SSD1351_BLUE,"cnt:%5dms log:%d",cnt0, loggingSDcard);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"insertSD:%d",insertSDcard);
		// SSD1351setCursor(2, 62);
		// // SSD1351printf(Font_7x10,SSD1351_BLUE,"encoder:%5d current%3d",encTotal,encCurrent);
		// SSD1351printf(Font_7x10,SSD1351_BLUE,"initSD:%d",initSDcard);

		if(swValRotary == 0x0)
		{
			MotorPwmOut(-500, -500, -500, -500);
		}
		else if (swValRotary == 0x1) 
		{
			MotorPwmOut(500, 500, 500, 500);
		}

		if(cnt0 > 10000 && loggingSDcard)
		{
			loggingSDcard = 0;
			f_close(&file);
			SDcardEnd();
		}

	}
}
